#templatefile -v "1.0" -n "ImageFlow Black-  an iTunes style gallery." -d "Generated by a free Picasa template from www.paulvanroekel.nl"

define imageWidth 400
define imageHeight 400

define shadowedThumbnails 0

define thumbnailWidth 400
define thumbnailHeight 400

include xmlTemplate.tpl
include htmlTemplate.tpl

copy assets\